# .github/workflows/npm-publish.yml

name: Node.js Package

on: 
push:
  tags:
    - "*"

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]


    steps:
    - uses: actions/checkout@v4
    - name: use Node.js $
      uses: actions/setup-node@v3
      with: 
      node-version: 18.12.1
      cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
    - run: npm test


  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: 
        node-version: 18.12.1
        registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm publish --governance
        env: 
         NODE_AUTH_TOKEN: $
